# frozen_string_literal: true
# SPDX-License-Identifier: Proprietary
#
# ASRFacet-Rb: Attack Surface Reconnaissance Framework
# Copyright (c) 2026 voltsparx
#
# Author: voltsparx
# Repository: https://github.com/voltsparx/ASRFacet-Rb
# Contact: voltsparx@gmail.com
# License: See LICENSE file in the project root
#
# This file is part of ASRFacet-Rb and is subject to the terms
# and conditions defined in the LICENSE file.

require_relative "../base_renderer"
require_relative "../runtime_detector"

module ASRFacet
  module Output
    module Ruby
      class TxtRenderer < BaseRenderer
        LINE = ("=" * 72).freeze
        DASH = ("-" * 72).freeze

        def render(output_path)
          write!(output_path, build)
          log_success("TXT", output_path)
        rescue StandardError => e
          raise ASRFacet::Error, "TXT render failed: #{e.message}"
        end

        private

        def build
          [
            header,
            summary_section,
            list_section("Discovered Subdomains", @store.subdomains),
            list_section("Identified IPs", @store.ips),
            ports_section,
            findings_section,
            list_section("JS Endpoints", @store.js_endpoints),
            charts_section,
            list_section("Errors", @store.errors.map { |entry| "[#{entry[:source]}] #{entry[:message]}" }),
            footer
          ].join("\n\n")
        end

        def header
          [LINE, report_title, "Target: #{@target}", "Generated: #{timestamp}", "Engine: #{RuntimeDetector.engine_label}", "Version: #{version}", LINE].join("\n")
        end

        def summary_section
          stats = @store.stats
          [title("Executive Summary"), "Subdomains: #{stats[:subdomains]}", "IPs: #{stats[:ips]}", "Findings: #{stats[:findings]}", "JS Endpoints: #{stats[:js_endpoints]}", "Errors: #{stats[:errors]}"].join("\n")
        end

        def list_section(name, values)
          lines = [title("#{name} (#{values.size})")]
          if values.empty?
            lines << "  (none)"
          else
            values.each { |value| lines << "  - #{value}" }
          end
          lines.join("\n")
        end

        def ports_section
          lines = [title("Open Ports")]
          if @store.ports.empty?
            lines << "  (none)"
          else
            @store.ports.each do |ip, ports|
              lines << "  #{ip}:"
              Array(ports).each do |port|
                lines << "    - #{port[:port]} [#{port[:service] || 'unknown'}] #{port[:banner]}"
              end
            end
          end
          lines.join("\n")
        end

        def findings_section
          lines = [title("Security Findings (#{sorted_findings.size})")]
          if sorted_findings.empty?
            lines << "  (none)"
          else
            sorted_findings.each_with_index do |finding, index|
              lines << "  [#{index + 1}] #{finding[:title] || 'Untitled'}"
              lines << "      Severity: #{finding[:severity] || 'informational'}"
              lines << "      Asset: #{finding[:asset] || finding[:host]}"
              lines << "      Description: #{finding[:description]}" if finding[:description]
            end
          end
          lines.join("\n")
        end

        def charts_section
          charts = @options[:charts] || {}
          lines = [title("Chart Data Summary")]
          Array(charts[:severity_distribution]).each do |entry|
            lines << "  Severity #{entry[:label]}: #{entry[:value]}"
          end
          Array(charts[:port_frequency]).each do |entry|
            lines << "  Port #{entry[:port]}: #{entry[:count]}"
          end
          lines.join("\n")
        end

        def footer
          [LINE, "Generated by ASRFacet-Rb v#{version}", "For authorized security research only.", LINE].join("\n")
        end

        def title(text)
          [DASH, text.upcase, DASH].join("\n")
        end
      end
    end
  end
end
