# frozen_string_literal: true
# For use only on systems you own or have explicit
# written authorization to test.
# SPDX-License-Identifier: Proprietary
#
# ASRFacet-Rb: Attack Surface Reconnaissance Framework
# Copyright (c) 2026 voltsparx
#
# Author: voltsparx
# Repository: https://github.com/voltsparx/ASRFacet-Rb
# Contact: voltsparx@gmail.com
# License: See LICENSE file in the project root
#
# This file is part of ASRFacet-Rb and is subject to the terms
# and conditions defined in the LICENSE file.

require_relative "asrfacet_rb/version"
require_relative "asrfacet_rb/metadata"
require_relative "asrfacet_rb/errors"
require_relative "asrfacet_rb/colors"
require_relative "asrfacet_rb/config"
require_relative "asrfacet_rb/logger"
require_relative "asrfacet_rb/structured_logger"
require_relative "asrfacet_rb/rate_limiter"
require_relative "asrfacet_rb/key_store"
require_relative "asrfacet_rb/profiles"
require_relative "asrfacet_rb/dry_run_printer"
require_relative "asrfacet_rb/progress_dashboard"
require_relative "asrfacet_rb/permutation_engine"
require_relative "asrfacet_rb/core/thread_safe"
require_relative "asrfacet_rb/core/warning_filter"
ASRFacet::Core::WarningFilter.install!
require_relative "asrfacet_rb/core/error_reporter"
require_relative "asrfacet_rb/core/integrity_checker"
require_relative "asrfacet_rb/core/deduplicator"
require_relative "asrfacet_rb/execution/thread_pool"
require_relative "asrfacet_rb/execution/contract"
require_relative "asrfacet_rb/execution/parallel_engine"
require_relative "asrfacet_rb/execution/async_engine"
require_relative "asrfacet_rb/execution/scheduler"
require_relative "asrfacet_rb/thread_pool"
require_relative "asrfacet_rb/result_store"
require_relative "asrfacet_rb/event_bus"
require_relative "asrfacet_rb/engine/event_bus"
require_relative "asrfacet_rb/engine/plugin_registry"
require_relative "asrfacet_rb/engine/dispatcher"
require_relative "asrfacet_rb/engine/engine"
require_relative "asrfacet_rb/core/finding"
require_relative "asrfacet_rb/core/option_dsl"
require_relative "asrfacet_rb/core/string_extensions"
require_relative "asrfacet_rb/core/circuit_breaker"
require_relative "asrfacet_rb/core/adaptive_rate_controller"
require_relative "asrfacet_rb/core/plugin_sdk"
require_relative "asrfacet_rb/http/custom_transport"
require_relative "asrfacet_rb/http/retryable_client"
require_relative "asrfacet_rb/core/target"
require_relative "asrfacet_rb/mixins/network"
require_relative "asrfacet_rb/core/knowledge_graph"
require_relative "asrfacet_rb/core/recon_memory"
require_relative "asrfacet_rb/core/scope_engine"
require_relative "asrfacet_rb/core/noise_filter"
require_relative "asrfacet_rb/intelligence/open_asset_model"
require_relative "asrfacet_rb/intelligence/asset_graph"
require_relative "asrfacet_rb/intelligence/session_manager"
require_relative "asrfacet_rb/intelligence/dns/dns_resolver"
require_relative "asrfacet_rb/intelligence/dns/dns_wildcard"
require_relative "asrfacet_rb/intelligence/dns/dns_permutator"
require_relative "asrfacet_rb/intelligence/dns/dns_brute_forcer"
require_relative "asrfacet_rb/intelligence/dns/zone_transfer"
require_relative "asrfacet_rb/intelligence/sources/base_source"
require_relative "asrfacet_rb/intelligence/sources/crtsh_source"
require_relative "asrfacet_rb/intelligence/sources/hackertarget_source"
require_relative "asrfacet_rb/intelligence/sources/wayback_source"
require_relative "asrfacet_rb/intelligence/sources/rapiddns_source"
require_relative "asrfacet_rb/intelligence/sources/alienvault_source"
require_relative "asrfacet_rb/intelligence/sources/bufferover_source"
require_relative "asrfacet_rb/intelligence/sources/urlscan_source"
require_relative "asrfacet_rb/intelligence/sources/commoncrawl_source"
require_relative "asrfacet_rb/intelligence/sources/virustotal_source"
require_relative "asrfacet_rb/intelligence/sources/securitytrails_source"
require_relative "asrfacet_rb/intelligence/sources/shodan_source"
require_relative "asrfacet_rb/intelligence/sources/censys_source"
require_relative "asrfacet_rb/intelligence/sources/github_source"
require_relative "asrfacet_rb/intelligence/sources/dnsdumpster_source"
require_relative "asrfacet_rb/intelligence/sources/threatcrowd_source"
require_relative "asrfacet_rb/intelligence/sources/whoisxmlapi_source"
require_relative "asrfacet_rb/intelligence/enrichment/whois_enricher"
require_relative "asrfacet_rb/intelligence/enrichment/asn_enricher"
require_relative "asrfacet_rb/intelligence/enrichment/certificate_enricher"
require_relative "asrfacet_rb/intelligence/enrichment/ip_enricher"
require_relative "asrfacet_rb/intelligence/enrichment/http_enricher"
require_relative "asrfacet_rb/intelligence/analysis/relationship_mapper"
require_relative "asrfacet_rb/intelligence/analysis/attack_surface"
require_relative "asrfacet_rb/intelligence/analysis/asset_differ"
require_relative "asrfacet_rb/scanner/timing"
require_relative "asrfacet_rb/scanner/results/port_result"
require_relative "asrfacet_rb/scanner/results/host_result"
require_relative "asrfacet_rb/scanner/results/scan_result"
require_relative "asrfacet_rb/scanner/verbose_logger"
require_relative "asrfacet_rb/scanner/probe_db"
require_relative "asrfacet_rb/scanner/result_adapter"
require_relative "asrfacet_rb/scanner/probes/tcp_prober"
require_relative "asrfacet_rb/scanner/probes/udp_prober"
require_relative "asrfacet_rb/scanner/probes/icmp_prober"
require_relative "asrfacet_rb/scanner/version_detector"
require_relative "asrfacet_rb/scanner/fingerprint_engine"
require_relative "asrfacet_rb/scanner/scan_context"
require_relative "asrfacet_rb/scanner/scan_types/base_scan"
require_relative "asrfacet_rb/scanner/scan_types/connect_scan"
require_relative "asrfacet_rb/scanner/scan_types/syn_scan"
require_relative "asrfacet_rb/scanner/scan_types/udp_scan"
require_relative "asrfacet_rb/scanner/scan_types/ack_scan"
require_relative "asrfacet_rb/scanner/scan_types/fin_scan"
require_relative "asrfacet_rb/scanner/scan_types/null_scan"
require_relative "asrfacet_rb/scanner/scan_types/xmas_scan"
require_relative "asrfacet_rb/scanner/scan_types/window_scan"
require_relative "asrfacet_rb/scanner/scan_types/maimon_scan"
require_relative "asrfacet_rb/scanner/scan_types/ping_scan"
require_relative "asrfacet_rb/scanner/scan_types/service_scan"
require_relative "asrfacet_rb/scanner/scan_engine"
require_relative "asrfacet_rb/plugins/base"
require_relative "asrfacet_rb/plugins/dns_enrich_plugin"
require_relative "asrfacet_rb/passive/base_source"
require_relative "asrfacet_rb/passive/crtsh"
require_relative "asrfacet_rb/passive/hackertarget"
require_relative "asrfacet_rb/passive/wayback"
require_relative "asrfacet_rb/passive/rapiddns"
require_relative "asrfacet_rb/passive/alienvault"
require_relative "asrfacet_rb/passive/shodan"
require_relative "asrfacet_rb/passive/threatcrowd"
require_relative "asrfacet_rb/passive/bufferover"
require_relative "asrfacet_rb/sources/base_source"
require_relative "asrfacet_rb/sources/urlscan_source"
require_relative "asrfacet_rb/sources/commoncrawl_source"
require_relative "asrfacet_rb/sources/virustotal_source"
require_relative "asrfacet_rb/sources/securitytrails_source"
require_relative "asrfacet_rb/passive/runner"
require_relative "asrfacet_rb/engines/dns_engine"
require_relative "asrfacet_rb/engines/permutation_engine"
require_relative "asrfacet_rb/engines/cert_engine"
require_relative "asrfacet_rb/engines/whois_engine"
require_relative "asrfacet_rb/engines/asn_engine"
require_relative "asrfacet_rb/engines/crawl_engine"
require_relative "asrfacet_rb/engines/port_engine"
require_relative "asrfacet_rb/engines/http_engine"
require_relative "asrfacet_rb/engines/vuln_engine"
require_relative "asrfacet_rb/engines/js_endpoint_engine"
require_relative "asrfacet_rb/engines/headless_engine"
require_relative "asrfacet_rb/engines/correlation_engine"
require_relative "asrfacet_rb/engines/asset_scorer"
require_relative "asrfacet_rb/engines/monitoring_engine"
require_relative "asrfacet_rb/engines/probabilistic_subdomain_engine"
require_relative "asrfacet_rb/busters/base_buster"
require_relative "asrfacet_rb/busters/dns_buster"
require_relative "asrfacet_rb/busters/dir_buster"
require_relative "asrfacet_rb/busters/vhost_buster"
require_relative "asrfacet_rb/pipeline"
require_relative "asrfacet_rb/output/base_formatter"
require_relative "asrfacet_rb/output/runtime_detector"
require_relative "asrfacet_rb/output/base_renderer"
require_relative "asrfacet_rb/output/chart_data_builder"
require_relative "asrfacet_rb/output/cli_formatter"
require_relative "asrfacet_rb/output/json_formatter"
require_relative "asrfacet_rb/output/sarif_formatter"
require_relative "asrfacet_rb/output/jsonl_stream"
require_relative "asrfacet_rb/output/txt_formatter"
require_relative "asrfacet_rb/output/html_formatter"
require_relative "asrfacet_rb/output/change_tracker"
require_relative "asrfacet_rb/output/ruby/txt_renderer"
require_relative "asrfacet_rb/output/ruby/html_renderer"
require_relative "asrfacet_rb/output/ruby/json_renderer"
require_relative "asrfacet_rb/output/ruby/csv_renderer"
require_relative "asrfacet_rb/output/ruby/pdf_renderer"
require_relative "asrfacet_rb/output/ruby/docx_renderer"
require_relative "asrfacet_rb/output/js/js_pdf_bridge"
require_relative "asrfacet_rb/output/js/js_docx_bridge"
require_relative "asrfacet_rb/output/output_router"
require_relative "asrfacet_rb/renderers/sarif_renderer"
require_relative "asrfacet_rb/graph/exporter"
require_relative "asrfacet_rb/notifiers/webhook_notifier"
require_relative "asrfacet_rb/web/session_store"
require_relative "asrfacet_rb/web/session_runner"
require_relative "asrfacet_rb/web/server"
require_relative "asrfacet_rb/lab/template_server"
require_relative "asrfacet_rb/ui/banner"
require_relative "asrfacet_rb/ui/about"
require_relative "asrfacet_rb/ui/first_run_guide"
require_relative "asrfacet_rb/ui/manual"
require_relative "asrfacet_rb/ui/help_catalog"
require_relative "asrfacet_rb/ui/console"
require_relative "asrfacet_rb/ui/cli"
require_relative "asrfacet_rb/ui/interactive"

ASRFacet::Core::PluginSDK.register_namespace(ASRFacet::Passive, type: :passive_source)
ASRFacet::Core::PluginSDK.register_namespace(ASRFacet::Busters, type: :buster)
ASRFacet::Core::PluginSDK.register_namespace(ASRFacet::Output, type: :formatter)
ASRFacet::Core::PluginSDK.register_namespace(ASRFacet::Engines)
