# SPDX-License-Identifier: Proprietary
#
# ASRFacet-Rb: Attack Surface Reconnaissance Framework
# Copyright (c) 2026 voltsparx
#
# Author: voltsparx
# Repository: https://github.com/voltsparx/ASRFacet-Rb
# Contact: voltsparx@gmail.com
# License: See LICENSE file in the project root
#
# This file is part of ASRFacet-Rb and is subject to the terms
# and conditions defined in the LICENSE file.

require_relative "asrfacet_rb/version"
require_relative "asrfacet_rb/metadata"
require_relative "asrfacet_rb/colors"
require_relative "asrfacet_rb/config"
require_relative "asrfacet_rb/logger"
require_relative "asrfacet_rb/core/thread_safe"
require_relative "asrfacet_rb/core/error_reporter"
require_relative "asrfacet_rb/core/integrity_checker"
require_relative "asrfacet_rb/execution/thread_pool"
require_relative "asrfacet_rb/execution/parallel_engine"
require_relative "asrfacet_rb/execution/async_engine"
require_relative "asrfacet_rb/execution/scheduler"
require_relative "asrfacet_rb/thread_pool"
require_relative "asrfacet_rb/result_store"
require_relative "asrfacet_rb/event_bus"
require_relative "asrfacet_rb/core/finding"
require_relative "asrfacet_rb/core/option_dsl"
require_relative "asrfacet_rb/core/string_extensions"
require_relative "asrfacet_rb/core/circuit_breaker"
require_relative "asrfacet_rb/core/adaptive_rate_controller"
require_relative "asrfacet_rb/core/plugin_sdk"
require_relative "asrfacet_rb/http/custom_transport"
require_relative "asrfacet_rb/http/retryable_client"
require_relative "asrfacet_rb/core/target"
require_relative "asrfacet_rb/mixins/network"
require_relative "asrfacet_rb/core/knowledge_graph"
require_relative "asrfacet_rb/core/recon_memory"
require_relative "asrfacet_rb/core/scope_engine"
require_relative "asrfacet_rb/core/noise_filter"
require_relative "asrfacet_rb/passive/base_source"
require_relative "asrfacet_rb/passive/crtsh"
require_relative "asrfacet_rb/passive/hackertarget"
require_relative "asrfacet_rb/passive/wayback"
require_relative "asrfacet_rb/passive/rapiddns"
require_relative "asrfacet_rb/passive/alienvault"
require_relative "asrfacet_rb/passive/shodan"
require_relative "asrfacet_rb/passive/threatcrowd"
require_relative "asrfacet_rb/passive/bufferover"
require_relative "asrfacet_rb/passive/runner"
require_relative "asrfacet_rb/engines/dns_engine"
require_relative "asrfacet_rb/engines/permutation_engine"
require_relative "asrfacet_rb/engines/cert_engine"
require_relative "asrfacet_rb/engines/whois_engine"
require_relative "asrfacet_rb/engines/asn_engine"
require_relative "asrfacet_rb/engines/crawl_engine"
require_relative "asrfacet_rb/engines/port_engine"
require_relative "asrfacet_rb/engines/http_engine"
require_relative "asrfacet_rb/engines/vuln_engine"
require_relative "asrfacet_rb/engines/js_endpoint_engine"
require_relative "asrfacet_rb/engines/headless_engine"
require_relative "asrfacet_rb/engines/correlation_engine"
require_relative "asrfacet_rb/engines/asset_scorer"
require_relative "asrfacet_rb/engines/monitoring_engine"
require_relative "asrfacet_rb/engines/probabilistic_subdomain_engine"
require_relative "asrfacet_rb/busters/base_buster"
require_relative "asrfacet_rb/busters/dns_buster"
require_relative "asrfacet_rb/busters/dir_buster"
require_relative "asrfacet_rb/busters/vhost_buster"
require_relative "asrfacet_rb/pipeline"
require_relative "asrfacet_rb/output/base_formatter"
require_relative "asrfacet_rb/output/cli_formatter"
require_relative "asrfacet_rb/output/json_formatter"
require_relative "asrfacet_rb/output/jsonl_stream"
require_relative "asrfacet_rb/output/txt_formatter"
require_relative "asrfacet_rb/output/html_formatter"
require_relative "asrfacet_rb/output/change_tracker"
require_relative "asrfacet_rb/notifiers/webhook_notifier"
require_relative "asrfacet_rb/web/session_store"
require_relative "asrfacet_rb/web/session_runner"
require_relative "asrfacet_rb/web/server"
require_relative "asrfacet_rb/lab/template_server"
require_relative "asrfacet_rb/ui/banner"
require_relative "asrfacet_rb/ui/about"
require_relative "asrfacet_rb/ui/first_run_guide"
require_relative "asrfacet_rb/ui/manual"
require_relative "asrfacet_rb/ui/help_catalog"
require_relative "asrfacet_rb/ui/console"
require_relative "asrfacet_rb/ui/cli"
require_relative "asrfacet_rb/ui/interactive"

ASRFacet::Core::PluginSDK.register_namespace(ASRFacet::Passive, type: :passive_source)
ASRFacet::Core::PluginSDK.register_namespace(ASRFacet::Busters, type: :buster)
ASRFacet::Core::PluginSDK.register_namespace(ASRFacet::Output, type: :formatter)
ASRFacet::Core::PluginSDK.register_namespace(ASRFacet::Engines)
